# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Automação DatoCMS - NextJS"
client_id = "5cb8472fde9abb97f6c9ceec6fce8a6b"
application_url = "https://enterprise-next-datocms.vercel.app"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,write_products,read_locales,read_translations,write_translations,unauthenticated_write_checkouts,unauthenticated_read_checkouts,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,unauthenticated_read_content"
optional_scopes = [ ]
use_legacy_install_flow = false

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shopify"
  topics = [ "products/create", "products/update", "collections/create", "collections/update" ]

[auth]
redirect_urls = [ ]
